import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/shared/header/Header";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Providers children={children}></Providers>
      </body>
    </html>
  );
}
