import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/shared/header/Header";
import { Providers } from "./Providers";
import { hind_siliguri } from "@/lib/Font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hind_siliguri.className}`} >
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
